---
# tasks file for frontend
- name: Install nginx on Ubuntu
  ansible.builtin.apt:
    name: nginx
    state: present
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Create index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Reload nginx
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Create nginx configuration
  ansible.builtin.copy:
    src: default.conf
    dest: /etc/nginx/sites-available/default
  notify: Reload nginx
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Enable nginx configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Reload nginx
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Ensure nginx is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  when: ansible_facts['distribution'] == 'Ubuntu'

